### ISSUE TITLE
PromptTemplates should be template literals

### ISSUE THREAD

**Issue by BLamy** [cfortuner/promptable#19]
This library is cool but I feel like prompt templates should just use the language instead of being their own object. 

https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html

https://www.typescriptlang.org/play?#code/C4TwDgpgBACg9hAtgFTmAlgYwM5QLxQBEANnAG4SFQA+RAZgE7oQB2AJtgBbphW2F1SAdwgNshAFBSJoSLASIYDOIjDBkSMMQCGwaAQAGAdSZ6o2qGAXmARnACuwKABIA3vCSoMOAL4GpQA

<img width="941" alt="image" src="https://user-images.githubusercontent.com/324928/219131776-44abcf4c-b86a-4587-8949-56695abab7c0.png">

Maybe use zod to enforce at runtime.

**Comment by cfortuner** [comment]
Hey! Thanks for the feedback.

What would the usage look like for this?

Definitely looking to simplify prompt creation for people so I like this direction.

**Comment by BLamy** [comment]
Right now when I call prompt.format I will get back text which is typed as a string then you pass that string to openAI's generate function. I think it would be better if you wrapped generate and made it generic so that when i call `.generate` it expects the string that is passed in to be one of the the strings in the union and will give a type level error if you try to generate a prompt that isn't allowed. 


https://www.typescriptlang.org/play?#code/C4TwDgpgBA8pB2BBAklAvFA3gKCnqA5hPBAE4CGwEAXFABRikD2AtmMLQM7CkCW8BAJToAfFG58B2AL7ZsAYwA25TpygAFZm2DkARoogAeTa3YAVCG2VU1EAB5V4AEzUT+BMTnxRGvAG6U0EwI5Ly0cMQoANxy3vJM8BIArvLATKR0wcSh4Qgowl7e+MAAFrycAHRZ8KHoUNWhMd6yuPhEJBRUDFrstCbaFlaBnAWtRVCkEMBJpPBQpeVVIbwV7WSB3abAgk34si3YAPSHGkyWGj3A2KCQp5ZmwbzyahgARIpMfhCvUAA+UK8AGZ8YguMpgH7-IEfADuZE4r2u4Gg6jOLH65ksYGs0AwAAMAOp8KhQcg+NGk3RMJLAKAAEkwqPuj2e0jxRxOACkmABrFGXJG3bl8szIl4AwFJeDwECQgFOchOOWvJxJFi6RE3aDCiAY4CDbGBOp4iyKRRQFjQMkMnWiyCcaRQHXsuQKBLcHyXPQGOokGEXLbeoxM9GXA04v5O3m6sNYnEiOh+2B5ZB0chgXgAaQgIEEO1dBYLjED+ggq2I6y6gkLQA

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/324928/219137243-74bd6e00-7a4f-46b3-b4cc-3277f2f6d2c9.png">

**Comment by cfortuner** [comment]
@BLamy 

I really like the idea of constraining our inputs to only valid types, although it might be overkill at this stage.

I do think we should ensure that the generate function enforces the variables of a prompt are provided as a parameter.

We do this with generics today in the Prompt class, but I'm open to simplifying the Prompt class into functions like you proposed that take in variables instead.

Gonna leave this open for a bit and see if anyone else has input here.

**Comment by BLamy** [comment]
Sounds great. I'll keep playing around with things. My opinion may change once I have more context.

**Comment by emfastic** [comment]
@BLamy Agree with the idea of constraining inputs to only be valid types; right now I have limited utility in having typed variables like the PoemTopics example as most of what I'm doing is based on user inputs fed into a predefined prompt.

**Comment by BLamy** [comment]
@emfastic I'd argue you should be sanitizing your user input similar to how you would sanitize data going into a sql query. This approach really shines when you use zod to validate user input

https://stackblitz.com/edit/node-ycgnwj?file=app.ts

<img width="785" alt="image" src="https://user-images.githubusercontent.com/324928/219817094-a819d39c-081b-443c-8a05-b0071b7c359c.png">

**Comment by cfortuner** [comment]
The issue with this @BLamy , is that LLMs like openai are built to allow the user to write any string / text input and return valid text output.

For many use cases, constraining the inputs and output to specific text values doesn't make sense.

Instead, it would be more useful for validating that a Prompt is provided with the correct input variables based on the {{variable}} inside of the text.

Have a look at this: https://github.com/microsoft/prompt-engine

I'd love to hear if you have any opinions about it!

**Comment by BLamy** [comment]
> Have a look at this: https://github.com/microsoft/prompt-engine

Will take a look.

> Instead, it would be more useful for validating that a Prompt is provided with the correct input variables based on the {{variable}} inside of the text.

You can [S.Split](https://github.com/millsp/ts-toolbelt/blob/master/sources/String/Split.ts) on `{{` and then infer up until `}}`.     [TS Playground Example:](https://www.typescriptlang.org/play?#code/C4TwDgpgBAymA2BLYAeGUIA9gQHYBMBnKQ4AJ0VwHMAaKAEQ2zyJPMqoD4oBeNi6kxwFiMAFBQoAfn4cA2gF0JUAFywhLYgHItymYuVr0WYawAGAEgDelAGYQyUACoBfa-Tc3c9xwFUXZnpQck50AHQRcEiovnT0nEqSanIwCgDcYmKgkFAAothkAIYAxsBOEAC2CIU4AAqFRRWEKE71wAAWGiKy1Nx8VspyANJQlLAIyC1t7XRaVlZanHK4AK4VAEYOClCFxCMmmlCWXj5QtS4X1qQCVAHKkjK196pQuBAAbltq1xwZLhliWwrXClRAAe1wUCoeAcNQgLS6rB+vQAFMowGQwVVgGpQuiGoUmmp8uQSmVKtU6gSmi1OGIAJRQKwuTLFCGkKAYrFgclVeBw3hQLTleDwKAVaCFJlWABWYIA1hAnOAIBcoHLFWEtBloW8ijgUVzseU+XC6FZ1QqlSq1AAiHCkW1QFz0sS62EGo08k2UiDmqAOnFC3a2LTO+lpKAAeijUBQAFoAyqMGRMWQ3TD9RBDZjjRT+Th-eHIzG44mAO6IUVQdqFT47FbAMFQNl8iA4KC2MGORUgV6EiCEMRAA)

<img width="683" alt="image" src="https://user-images.githubusercontent.com/324928/219978208-dfb6a7b2-16aa-4344-860b-e3445087d68b.png">

```ts
type Split<S extends string, D extends string> = string extends S
  ? string[]
  : S extends ''
  ? []
  : S extends `${infer T}${D}${infer U}`
  ? [T, ...Split<U, D>]
  : [S];

type ExtractTemplateParams<TPath extends string> = {
  [K in Split<TPath, '{{'>[number] as K extends `${infer P}}}${string}`
    ? P
    : never]: string;
};

function generate<T extends string>(
  prompt: T,
  params: ExtractTemplateParams<T>
) {}

const promptTemplate = 'Tell me a {{jokeType}} joke.';
generate(promptTemplate, { jokeType: "test" })
generate(promptTemplate, { test: 'asf' }); // <- type error
generate(promptTemplate, {  }); // <- will have auto complete for key names
```

**Comment by cfortuner** [comment]
Okay now that is cool. Didn't know about Split but definitely interested in this now! Thanks for sharing this @BLamy

**Comment by BLamy** [comment]
I've also seen people do something similar with recurison. [For Example](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCiIZQIYGMYBq2UAltgEYA2wAzgDwAqcoMwAdgCY1w1YlsBzAHxwAvACg4cJi3Zc4AAwAkAb34AzYFDgAZYOpgBfFStUatcAHLYAtsEMOzbTdoBKJAQAsjCyVLgA-HAqcADaANJw-NKkNgDKYHi0dNZ2QgC6AFw8fIJwhnAAZOiYOPhEpBTU9O5eMCKFfv7+GFh4hMRkVMl6BkJNcNkqhgDc4uKgkLAIyKgMsQlJ9HHMmHLcvKSCIqJwK7Kc3ApwTi5wrrQ+fkHzJPGJuMkXvP1S2ftrh4qnFs9GitcYndFo8apdXoM9mNxEgUKtbGBqGI-K0yh1Kt16AAiAASwEolAgcBsiDgbFsqBI3BM5LsDjg2E4UQA5DZgipsAJ7AVEMBiNwIJQOAA6YmkzwAVxo5EZHCkAHdsNSVBwIPhoA4sUIxkA)

<img width="782" alt="image" src="https://user-images.githubusercontent.com/324928/219996786-3256c750-2b71-4914-bbdb-accd55130785.png">

https://github.com/Necmttn/langflow/blob/3bbfd447fbd721b6220a78da8111bd6591c5ce29/packages/prompt/src/index.ts#L5-L18

**Comment by yourbuddyconner** [comment]
Ok this is exactly what I have been ideating on how cool. I think leaning into the native type system to build a composable and *type-safe* prompt system is exactly why the choice of TS is a good one. 

Already the simple prompt parameter name validation has been super-helpful, but I want to go 2-3 steps further in very much the same way as the original idea in this thread, though I am sure an abstraction can be achieved that uses less type arithmetic and is more abstract. 

The pipeline I am working on presently is a GEtL (Generate, Extract/Transform, Load) pipeline and I am producing an `interface` at each step of generation such that the extracted output is constrained to the format the next step in the workflow expects such that the subsequent step can use output from the previous prompt in a highly structured way. 

If I could pass the full complex input interface and a similar or identical output interface to the prompt engine that would be super sick and provide even more efficiency gains than the current prompt abstraction. From there it would be pretty trivial to generate prompts and types dynamically on the fly which opens up some real juicy ux opportunities.

**Comment by cfortuner** [comment]
Would love to see an example @yourbuddyconner 

@BLamy we're working on adopting this 🙇‍♂️
