### ISSUE TITLE
Promptable web tracing dropdown doesn't close

### ISSUE THREAD

**Issue by justinliang1020** [cfortuner/promptable#30]
Promptable tracing UI dropdown doesn't close when clicking the dropdown arrow after opening.

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/54543035/219723386-d2e50d77-2285-40fe-9ca3-d7d00edf0e13.png">

Relevant info:
- docs: https://github.com/cfortuner/promptable/blob/main/apps/docs/docs/modules/tracing.md
- source code: https://github.com/cfortuner/promptable/blob/main/apps/web/src/components/Content.tsx#L73

**Comment by cfortuner** [comment]
closing this for now while we rethink tracing a bit
