### ISSUE TITLE
QuestionAnswerChain not exported from promptable

### ISSUE THREAD

**Issue by braco** [cfortuner/promptable#42]
and @promptable/promptable not found

is this not ready to be used?

**Comment by cfortuner** [comment]
Hey! Yeah we're changing the package from promptable -> @promptable/promptable and we haven't released it yet. 

Should be available next week.

**Comment by braco** [comment]
Thanks, are one of these branches semi-complete?

**Comment by cfortuner** [comment]
Main is most up to date as of now.

Feel free to dm me in discord if you have any questions/want help with something!
