### ISSUE TITLE
Support ChatGPT API

### ISSUE THREAD

**Issue by 0oj** [cfortuner/promptable#45]
Add support for the new [Chat Completions API](https://platform.openai.com/docs/guides/chat/introduction) by OpenAI.

**Comment by cfortuner** [comment]
Hey! I just added support for it.

I'm working on a big change to the apis, so I haven't made a release for it yet but its coming very soon!

**Comment by cfortuner** [comment]
https://twitter.com/colinfortuner/status/1631011216092024838?s=20
